"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_EDITOR_SETTINGS = exports.LANGUAGE_MAP = exports.API_ROUTES = exports.WS_EVENTS = void 0;
exports.WS_EVENTS = {
    CONNECT: 'connect',
    DISCONNECT: 'disconnect',
    FILE_CHANGED: 'file:changed',
    FILE_CREATED: 'file:created',
    FILE_DELETED: 'file:deleted',
    FILE_RENAMED: 'file:renamed',
    TERMINAL_OUTPUT: 'terminal:output',
    TERMINAL_INPUT: 'terminal:input',
    TERMINAL_RESIZE: 'terminal:resize',
    TERMINAL_CLOSE: 'terminal:close',
    OPENCODE_MESSAGE: 'opencode:message',
    OPENCODE_STREAM: 'opencode:stream',
    OPENCODE_COMPLETE: 'opencode:complete',
    OPENCODE_ERROR: 'opencode:error',
    DEPLOY_STATUS: 'deploy:status',
    DEPLOY_LOG: 'deploy:log',
    DEPLOY_COMPLETE: 'deploy:complete',
    USER_JOINED: 'user:joined',
    USER_LEFT: 'user:left',
    CURSOR_MOVED: 'cursor:moved',
};
exports.API_ROUTES = {
    AUTH: {
        GITHUB: '/auth/github',
        GITHUB_CALLBACK: '/auth/github/callback',
        ME: '/auth/me',
        LOGOUT: '/auth/logout',
    },
    PROJECTS: {
        BASE: '/projects',
        BY_ID: (id) => `/projects/${id}`,
        FILES: (id) => `/projects/${id}/files`,
        FILE: (id, path) => `/projects/${id}/files/${path}`,
    },
    GITHUB: {
        REPOS: '/github/repos',
        CLONE: '/github/clone',
        PUSH: '/github/push',
        PULL: '/github/pull',
        BRANCHES: (repo) => `/github/repos/${repo}/branches`,
    },
    OPENCODE: {
        CHAT: '/opencode/chat',
        STREAM: '/opencode/stream',
    },
    RAILWAY: {
        DEPLOY: '/railway/deploy',
        DEPLOYMENTS: '/railway/deployments',
        LOGS: (id) => `/railway/logs/${id}`,
    },
};
exports.LANGUAGE_MAP = {
    '.js': 'javascript',
    '.jsx': 'javascript',
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.py': 'python',
    '.rb': 'ruby',
    '.go': 'go',
    '.rs': 'rust',
    '.java': 'java',
    '.cpp': 'cpp',
    '.c': 'c',
    '.cs': 'csharp',
    '.php': 'php',
    '.html': 'html',
    '.css': 'css',
    '.scss': 'scss',
    '.sass': 'sass',
    '.less': 'less',
    '.json': 'json',
    '.xml': 'xml',
    '.yaml': 'yaml',
    '.yml': 'yaml',
    '.md': 'markdown',
    '.sql': 'sql',
    '.sh': 'shell',
    '.bash': 'shell',
    '.zsh': 'shell',
    '.dockerfile': 'dockerfile',
    '.graphql': 'graphql',
    '.vue': 'vue',
    '.svelte': 'svelte',
};
exports.DEFAULT_EDITOR_SETTINGS = {
    theme: 'vs-dark',
    fontSize: 14,
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    tabSize: 2,
    insertSpaces: true,
    wordWrap: 'on',
    minimap: { enabled: true },
    lineNumbers: 'on',
    scrollBeyondLastLine: false,
    automaticLayout: true,
};
//# sourceMappingURL=constants.js.map